from agents.llm import get_llm


def generate_report(
    market_results: dict,
    domain_results: dict,
) -> str:

    llm = get_llm()

    prompt = f"""
You are the Final Report Agent.

Two KV cache optimization technologies were selected
DIRECTLY BY HUMANS from the provided document pool.

Selected technologies:
- Software approach: KIVI
- Hardware/system approach: InfiniGen

Technology selection is NOT an agent task.

The assignment evaluates ONLY:
1. Market applicability
2. Domain applicability

Target domain:
Data center / cloud-based long-context LLM serving

Below are results generated by specialized agents.

================ MARKET RESULTS ================

KIVI:
{market_results['KIVI']['analysis']}

InfiniGen:
{market_results['InfiniGen']['analysis']}

================ DOMAIN RESULTS ================

KIVI:
{domain_results['KIVI']['analysis']}

InfiniGen:
{domain_results['InfiniGen']['analysis']}

================================================

Generate a neutral comparative evaluation report in Korean.

IMPORTANT RULES:

1. Never choose a winner.
2. Never recommend one technology over another.
3. Clearly separate facts from interpretation.
4. Highlight where market and domain perspectives differ.
5. Explicitly state evidence limitations.
6. Explain trade-offs.
7. The report must reflect that technology selection
   was Human-based, not Agent-based.

Use this structure:

# SUMMARY

Summarize the major differences in no more than several paragraphs.

# 1. 분석 배경

Explain KV cache bottleneck and why the comparison matters.

# 2. 대상 기술 및 선정 방식

State explicitly:

- Selection method: Human-based
- SW technology: KIVI
- HW/system technology: InfiniGen

Explain why the two represent different approaches.

# 3. 기술 개요

## 3.1 KIVI
## 3.2 InfiniGen

# 4. 시장성 관점 평가

## 4.1 KIVI
## 4.2 InfiniGen
## 4.3 시장성 관점 비교

# 5. 도메인 적용 관점 평가

Target:
Data center / cloud-based long-context LLM serving

## 5.1 KIVI
## 5.2 InfiniGen
## 5.3 도메인 관점 비교

# 6. 관점 간 비교 및 시사점

Focus on trade-offs and conflicts between perspectives.

# 7. 한계점

Include:
- analysis based mainly on public research papers
- limited evidence for real commercial adoption
- market conclusions may include inference
- publication-to-commercialization time lag
- RAG retrieval limitations

# REFERENCE

List the two primary papers:
- KIVI
- InfiniGen

Do not fabricate references.
"""

    response = llm.invoke(prompt)

    return response.content
